/* Daily Ten — 固定內容：XP 表、完成畫面身分句、SETUP 影片清單。M1 自 index.html 原樣搬出。 */
export const XP={full:10,cycle:15,boss:20,rest:5,rain:5,minimal:3};
export const IDENTITY=['你是每天訓練的人。','紀律就是自由。','出席，就是勝利的八成。','弱是選項，你沒選它。','今天的你，比昨天強一點。'];
export const VIDEOS=[
  ['— 十動作 —',''],
  ['貓牛式 Cat-Cow','cat cow exercise tutorial'],
  ['90/90 髖旋轉','90 90 hip switch mobility'],
  ['深蹲蹲坐 Deep Squat Hold','deep squat hold mobility'],
  ['靠牆滑臂 Wall Slides','wall slides shoulder mobility'],
  ['穿針式 Thread the Needle','thread the needle stretch'],
  ['臀橋 Glute Bridge','glute bridge form'],
  ['伏地挺身（HRP 標準）','hand release push up form ACFT'],
  ['深蹲 Squat','bodyweight squat form'],
  ['提踵 Calf Raise','calf raise form'],
  ['跪姿伏地挺身（保底替代）','knee push up form'],
  ['平板支撐（AFT 標準）','ACFT plank standard form'],
  ['— 伸展 B / C 組新增 —',''],
  ['嬰兒式側伸展','side child pose stretch'],
  ['世界最強伸展','worlds greatest stretch tutorial'],
  ['下犬↔上犬流動','downward dog to upward dog flow'],
  ['鴿式 Pigeon Pose','pigeon pose hip stretch'],
  ['躺姿脊椎扭轉','supine spinal twist stretch'],
  ['— 肩推鏈 —',''],
  ['俯臥 Y 舉','prone y t w raise shoulder'],
  ['俯臥 T 舉','prone y t w raise shoulder'],
  ['俯臥 W 舉','prone y t w raise shoulder'],
  ['派克伏地挺身','pike push up form'],
  ['腳抬高派克伏地挺身','elevated pike push up progression'],
  ['靠牆倒立撐','wall handstand hold beginner'],
  ['靠牆倒立肩推','wall handstand push up progression'],
  ['反向雪天使','reverse snow angel prone exercise'],
  ['平板肩點','plank shoulder taps form'],
  ['熊爬','bear crawl hold form'],
  ['假直立伏地挺身','pseudo planche push up tutorial'],
  ['— 下肢後鏈 —',''],
  ['分腿蹲 Split Squat','split squat bodyweight form'],
  ['單腳臀橋','single leg glute bridge form'],
  ['靠牆深蹲靜態 Wall Sit','wall sit form'],
  ['跪姿離心腿後彎舉','kneeling eccentric hamstring curl no equipment'],
  ['死蟲式 Dead Bug','dead bug core exercise'],
  ['單腳提踵','single leg calf raise form'],
  ['深蹲跳','squat jump form'],
  ['— 彈力帶動作 —',''],
  ['彈力帶划船','resistance band row form'],
  ['彈力帶直臂下拉','resistance band straight arm lat pulldown'],
  ['彈力帶面拉','resistance band face pull form'],
  ['彈力帶開肩','resistance band pull apart form'],
  ['彈力帶肩外旋','resistance band external rotation shoulder'],
  ['彈力帶肩上推','resistance band overhead press form'],
  ['彈力帶側平舉','resistance band lateral raise form'],
  ['彈力帶三頭下壓','resistance band triceps extension'],
  ['彈力帶二頭彎舉','resistance band biceps curl form'],
  ['彈力帶羅馬尼亞硬舉','resistance band romanian deadlift form'],
  ['— 徒手替代（出差沒帶時）—',''],
  ['毛巾划船（門把）','towel row door handle no equipment'],
  ['超人式划船','superman row prone back exercise'],
  ['超人式停留','superman hold exercise'],
  ['毛巾直臂下拉','towel lat pulldown self resistance'],
  ['反向平板 Reverse Plank','reverse plank form'],
  ['側平板 Side Plank','side plank form'],
  ['— 雨天室內有氧 —',''],
  ['波比跳 Burpee','burpee form'],
  ['開合跳 Jumping Jack','jumping jacks form']
];
